[package]
name = "visort"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
visort-core = { path = "../visort-core" }
bevy = { version = "0.9" }
bevy_egui = "0.17"
rand = "0.8"
